# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Tab\JsonEditor\GetMovieData\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_get_htmls = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_htmls.setGeometry(QtCore.QRect(350, 190, 241, 91))
        self.pushButton_get_htmls.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.pushButton_get_htmls.setObjectName("pushButton_get_htmls")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(380, 310, 171, 81))
        self.pushButton_clear.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.radioButton_film = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_film.setGeometry(QtCore.QRect(70, 30, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_film.setFont(font)
        self.radioButton_film.setChecked(True)
        self.radioButton_film.setObjectName("radioButton_film")
        self.radioButton_tv_show = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_tv_show.setEnabled(True)
        self.radioButton_tv_show.setGeometry(QtCore.QRect(180, 30, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_tv_show.setFont(font)
        self.radioButton_tv_show.setObjectName("radioButton_tv_show")
        self.checkBox_dubbed = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_dubbed.setGeometry(QtCore.QRect(410, 30, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_dubbed.setFont(font)
        self.checkBox_dubbed.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_dubbed.setChecked(True)
        self.checkBox_dubbed.setObjectName("checkBox_dubbed")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(370, 90, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_get_htmls.setText(_translate("MainWindow", "Get Htmls"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear List"))
        self.radioButton_film.setText(_translate("MainWindow", "Film"))
        self.radioButton_tv_show.setText(_translate("MainWindow", "TV Show"))
        self.checkBox_dubbed.setText(_translate("MainWindow", "Dubbed"))
        self.comboBox.setItemText(0, _translate("MainWindow", "30nama | IMDB"))
        self.comboBox.setItemText(1, _translate("MainWindow", "30nama"))
        self.comboBox.setItemText(2, _translate("MainWindow", "IMDB"))
        self.comboBox.setItemText(3, _translate("MainWindow", "HexDownload"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Doostiha"))
