# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Tab\JsonEditor\PosterCode\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(70, 140, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit_path.setFont(font)
        self.lineEdit_path.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.lineEdit_path.setText("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.pushButton_find = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_find.setGeometry(QtCore.QRect(210, 240, 281, 71))
        self.pushButton_find.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 16pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_find.setObjectName("pushButton_find")
        self.label_found = QtWidgets.QLabel(self.centralwidget)
        self.label_found.setGeometry(QtCore.QRect(160, 380, 161, 71))
        self.label_found.setStyleSheet("color: rgb(85, 0, 255);\n"
"font: 24pt \"Segoe UI\";")
        self.label_found.setObjectName("label_found")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("font: 26pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(30, 240, 151, 71))
        self.pushButton_clear.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"font: 16pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.listWidget_result = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_result.setGeometry(QtCore.QRect(580, 20, 101, 291))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listWidget_result.setFont(font)
        self.listWidget_result.setObjectName("listWidget_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Path :"))
        self.pushButton_find.setText(_translate("MainWindow", "Find"))
        self.label_found.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
